
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Currency.ToString(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExchangeRateAt.#ctor(System.DateTime,Pangea.Domain.Currency,Pangea.Domain.Currency,System.Decimal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Iban.#ctor(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.TryParse(System.String,Pangea.Domain.GpsLocation@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.PhoneNumber.TryParse(System.String,Pangea.Domain.PhoneNumber@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExtensionMethods.StringExtensions.ReplaceFirst(System.String,System.String,System.String,System.StringComparison)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "AV1704:Identifier contains one or more digits in its name", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.ApproximateDistanceTo(Pangea.Domain.GpsLocation)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Class Design", "AV1008:Class should not be static", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.EmojiFlag")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Class Design", "AV1008:Class should not be static", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.IbanParser")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1065:Do not raise exceptions in unexpected locations", Justification = "<Pending>", Scope = "member", Target = "~P:Pangea.Domain.AssemblyInformation.Item(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.Formatters.PhoneNumberAggregateFormatter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Member Design", "AV1130:Return type in method signature should be a collection interface instead of a concrete type", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRangeCollection.Ordered~Pangea.Domain.DateRangeCollection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRange.Day(System.DateTime)~Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRange.From(System.DateTime)~Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRange.Until(System.DateTime)~Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Fluent.DateRangeExtensions.Until(System.DateTime,System.DateTime)~Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Fluent.DateRangeExtensions.Until(System.DateTime,System.Int32,System.Int32,System.Int32)~Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.DefaultCountryProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.SimpleCountryCodeProvider")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Member Design", "AV1130:Return type in method signature should be a collection interface instead of a concrete type", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:Pangea.Domain.DateRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Isbn.ToString(System.IFormatProvider)~System.String")]

