
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1535:Missing block in case or default clause of switch statement", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.PhoneNumber.ToString(System.String,System.IFormatProvider)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Percentage.CompareTo(System.Object)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.DateRange.ReadXml(System.Xml.XmlReader)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Currency.ToString(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1535:Missing block in case or default clause of switch statement", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Currency.ToString(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Currency.#ctor(System.String,System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExchangeRate.#ctor(Pangea.Domain.Currency,Pangea.Domain.Currency)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExchangeRate.#ctor(Pangea.Domain.Currency,Pangea.Domain.Currency,System.Decimal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExchangeRateAt.#ctor(System.DateTime,Pangea.Domain.Currency,Pangea.Domain.Currency,System.Decimal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.IbanParser.Parse(System.String)~Pangea.Domain.IbanParser.ParsingResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.IbanParser.ParsingResult.ToString~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.IbanParser.Validate(Pangea.Domain.IbanParser.ParsingResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1561:Signature contains more than 3 parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Iban.#ctor(System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Checksums.ModChecksumCalculator.Calculate(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.Checksums.LuhnChecksumCalculator.Calculate(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.ExtensionMethods.EnumerableExtensions.Page``1(System.Collections.Generic.IEnumerable{``0},System.Int32)~System.Collections.Generic.IEnumerable{System.Collections.Generic.IEnumerable{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.CreditCard.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.#ctor(System.Decimal,System.Decimal)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.#ctor(System.Double,System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.ApproximateDistanceTo(Pangea.Domain.GpsLocation)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.Parse(System.String)~Pangea.Domain.GpsLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocationParser.Execute~Pangea.Domain.GpsLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocation.TryParse(System.String,Pangea.Domain.GpsLocation@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "AV1500:Member or local function contains more than 7 statements", Justification = "<Pending>", Scope = "member", Target = "~M:Pangea.Domain.GpsLocationParser.Execute~System.Tuple{System.Boolean,Pangea.Domain.GpsLocation}")]

